#!/bin/bash
if [ -L /opt/durapps/spark-dwine-helper/scale-set-helper ];then
rm -f /opt/durapps/spark-dwine-helper/scale-set-helper
fi

if [ -L /opt/deepinwine/tools/spark_run_v4.sh ];then
rm -f /opt/deepinwine/tools/spark_run_v4.sh
fi

echo "清理"