#!/bin/bash
if [ "$1" = "remove" ] || [ "$1" = "purge" ];then

echo "清理卸载残留"
BOTTLE_NAME="" #容器名
PACK_NAME=""   #软体套件名
MIME_TYPE=""
ACTIVEX_NAME=""
MAKE_AUTOSTART="" #开机时自动执行，需要实现请填写1
SEND_TO_DESKTOP="" #将启动图示从工作管理员copy至系统桌面，需要实现请填写1

make_autostart()
{
    for file in $(ls /home)
    do
        if [ -d "/home/${USER}/.config/autostart" ]
        then
            rm /home/${USER}/.config/autostart/$PACK_NAME.desktop
        fi
    done
}

send_to_desktop()
{
    for file in $(ls /home)
    do
        if [ -d "/home/${USER}/.config/autostart" ]
        then
            desktop=$(cat /etc/xdg/user-dirs.defaults | grep DESKTOP | awk -F= '{print $2}')
            if [ -d "/home/${USER}/$desktop" ]; then
                rm /home/${USER}/$desktop/$PACK_NAME*.desktop
            fi
        fi
    done
}

if [ -n "$MAKE_AUTOSTART" ]; then
    make_autostart
fi

if [ -n "$SEND_TO_DESKTOP" ]; then
    send_to_desktop
fi

if [ -n "$ACTIVEX_NAME" ]; then
    rm /usr/lib/mozilla/plugins/libpipelight-$ACTIVEX_NAME.so
fi


if [ -z $BOTTLE_NAME ];then
echo "W: 没有指定容器，跳过清理容器。请手动前往 ~/.deepinwine/ 下删除"
exit
fi

if [ -e /opt/deepinwine/tools/kill.sh ];then
/opt/deepinwine/tools/kill.sh $BOTTLE_NAME
###这里注意，如果没写BOTTLE_NAME,会把QQ杀了
fi

for username in $(ls /home)  
    do
      echo /home/$username
        if [ -d /home/$username/.deepinwine/$BOTTLE_NAME ]  
        then
        rm -rf /home/$username/.deepinwine/$BOTTLE_NAME
        fi
    done
else
echo "非卸载，跳过清理"
fi
