#!/bin/bash

PACK_NAME="" #软件包名
BOTTLE_NAME="" #容器名
ACTIVEX_NAME=""
MAKE_AUTOSTART="" #若需要开机自启，则填写1


make_autostart()
{
    for username in $(ls /home)
    do
        echo /home/$username
        if [ -d "/home/$username/.config/autostart" ]
        then
            cp /opt/apps/$PACK_NAME/entries/applications/$PACK_NAME.desktop /home/$username/.config/autostart/
            sed -i "s#%u#\"autostart\"#" /home/$username/.config/autostart/$PACK_NAME.desktop
        fi
    done
}



if [ -n "$MAKE_AUTOSTART" ]; then
    make_autostart
fi



if [ -n "$ACTIVEX_NAME" ]; then
    if [ ! -d "/usr/lib/mozilla/plugins" ];then
        mkdir -p /usr/lib/mozilla/plugins
    fi
    cp /usr/local/share/pipelight/libpipelight.so /usr/lib/mozilla/plugins/libpipelight-$ACTIVEX_NAME.so
fi

# Make sure the script returns 0
true


