#!/bin/sh

PACK_NAME="" #软体套件名
BOTTLE_NAME="" #容器名
MIME_TYPE="" 
ACTIVEX_NAME=""
MAKE_AUTOSTART=""
SEND_TO_DESKTOP=""

if [ -n "$MIME_TYPE" ]; then
    /opt/apps/$PACK_NAME/files/unregister_mimetype
fi

# Make sure the script returns 0
true


